name: foodu
description: "T Foodu - Food Delivery App"
publish_to: 'none'
version: 1.0.0+3


environment:
  sdk: ^3.5.0

  
  
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  gap: ^3.0.1
  intl: ^0.18.1
  logger: ^2.0.1
  ripple_wave: ^0.1.4
  slide_to_act: ^2.0.2
  image_picker: ^1.1.2
  otp_text_field: ^1.1.3
  flutter_slidable: ^3.1.1
  sliding_up_panel: ^2.0.0+1
  country_code_picker: ^3.0.0
  google_maps_flutter: ^2.13.1
  flutter_native_splash : ^2.3.2
  smooth_page_indicator: ^1.2.0+3
  flutter_launcher_icons: ^0.14.2
  connectivity_plus: ^6.0.5
  syncfusion_flutter_charts: ^31.1.19

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8


   # Firebase
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  google_sign_in: ^7.1.1
  flutter_facebook_auth: ^7.1.2
  firebase_storage: ^13.0.1
  geolocator: ^14.0.2
  flutter_dotenv: ^6.0.0
  url_launcher: ^6.3.1
  http: ^1.2.2
  webview_flutter: ^4.4.2
  flutter_inappwebview: ^6.1.5


 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/icons/
    - assets/icons/navigation_bar/
    - assets/images/on_boarding_images/
    - assets/images/welcome/
    - assets/images/let_you_in/
    - assets/images/profile/
    - assets/images/discount/
    - assets/images/category/
    - assets/images/food/
    - assets/images/search/
    - assets/images/restaurent/
    - assets/images/map/
    - assets/images/content/


  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
    - family: Luckiest Guy
      fonts:
        - asset: assets/fonts/LuckiestGuy-Regular.ttf
          weight: 400